version: "3.9"
services:
  migrations:
    build: .
    volumes:
      - .:/code
    command: python manage.py makemigrations

  migrate:
    build: .
    volumes:
      - .:/code
    command: python manage.py migrate

  web:
    build: .
    restart: always
    stdin_open: true
    tty: true
    command: bash -c "python manage.py runserver 0.0.0.0:8000"
    ports:
      - 8000:8000
    volumes:
      - .:/code
    depends_on:
      migrations:
        condition: service_completed_successfully
      migrate:
        condition: service_completed_successfully
