# Generated by Django 2.2 on 2023-01-26 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm_base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farm',
            name='municipality',
            field=models.CharField(max_length=255, verbose_name='Municipality'),
        ),
        migrations.AlterField(
            model_name='farm',
            name='state',
            field=models.CharField(max_length=255, verbose_name='State'),
        ),
    ]
